### ISSUE TITLE
Optimize WalletJob's StallMempool

### ISSUE THREAD

**Issue by nopara73** [nopara73/HBitcoin#11]
After: https://github.com/nopara73/HBitcoin/issues/6
Related: https://github.com/nopara73/HBitcoin/issues/10

It's not done in the best possible way, we could gain a second or two refactoring it.

**Comment by dangershony** [comment]
What's the purpose of mempool? Just storing unconfirmed trx associated to any tracked addresses right?

**Comment by nopara73** [comment]
Answered here: https://github.com/nopara73/HBitcoin/issues/10#issuecomment-290838162

**Comment by nopara73** [comment]
https://github.com/nopara73/HBitcoin/commit/987dfc6dc753708ee8e249bb4d44f039713d7fa6
